name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PWD }}

    - name: Pull Docker Image
      run: docker pull gabrielsantosbvc/3404-lab4:latest

    - name: Deploy to EC2
      run: |
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@ec2-3-137-165-148.us-east-2.compute.amazonaws.com "docker stop lab4 || true && docker rm lab4 || true"
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@ec2-3-137-165-148.us-east-2.compute.amazonaws.com "docker run -d -p 8090:80 --name lab4 gabrielsantosbvc/3404-lab4:latest"
